### ISSUE TITLE
replace curl with Symfony HttpClient or psr-18 client

### ISSUE THREAD

**Issue by tacman** [jefs42/libretranslate#6]
Great library, thanks for putting it together.

What do you think of replacing the low-level curl calls in doRequest with Symfony's HttpClient. Ideally, you'd be able to pass any psr-18 client, but I don't know how to do that, but I could replace the curl calls with HttpClient

The advantages -- much better control, automatic retries, better error messages, and configurable by the caller.

Unforunately, _doRequest is private, otherwise I'd just extend the  class and overwrite that method.

**Comment by tacman** [comment]
How about this.  Add a setClient() method that allows a psr-18 client, and if it's set, _doRequest uses it.  Otherwise, it falls back to curl, so it's an optional dependency.

I'm working on a lightweight Symfony bundle that wraps this calls, mostly so the host and port can be seamlessly saved in environment variables.  I was also thinking of adding an optional cache there, since I rarely want to retranslate.  I would certainly pass the symfony client by default if the option were available.

**Comment by jefs42** [comment]
Well, since the code is yours to use, you can of course change _doRequest to public and override it, or completely replace it with whatever you like. I'm just most familiar with using curl in what I mainly do. 

Since I set this up originally for my own needs, I of course coded it the way I'm used to, and without needing to go read up on documentation for doing it differently. I don't know how to use Symfony or it's HTTPClient. I have very limited knowledge of using GuzzleHTTP. And certainly don't know how to set up a "bring your own client". 

It was meant as a basic, easy to use connector since there was none for PHP and I needed to write my own. It certainly can be branched and re-coded in any number of ways... 
 - specifically setup to be included with a Symfony framework setup if that's what you use
 - could be incorporated into a plugin for CKEditor or similar
 
This only requires curl enabled in PHP (not counting ltmanage). It's bare bones, but only what is needed to actually work. That's also why it's on Github - take it, modify the heck out of it!
